# Generated by Django 6.0.5 on 2026-05-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoFerias',
            fields=[
                ('id_solicitacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_ferias', to='funcionarios.funcionario')),
            ],
            options={
                'db_table': 'solicitacao_ferias',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
