# Generated by Django 6.0.5 on 2026-05-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('pausa', 'Pausa')], max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_funcionario', models.ForeignKey(db_column='id_funcionario', on_delete=django.db.models.deletion.PROTECT, related_name='registros_ponto', to='funcionarios.funcionario')),
            ],
            options={
                'db_table': 'registros_ponto',
                'ordering': ['-data_hora'],
            },
        ),
    ]
