# Generated by Django 6.0.5 on 2026-05-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0002_alter_departamento_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nivel', models.SmallIntegerField(blank=True, choices=[(1, 'Júnior'), (2, 'Pleno'), (3, 'Sênior'), (4, 'Coordenador'), (5, 'Gerente'), (6, 'Diretor')], null=True)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='departamentos.departamento')),
            ],
            options={
                'db_table': 'cargo',
                'ordering': ['id_departamento', 'nivel', 'nome'],
            },
        ),
    ]
