# Generated by Django 6.0.5 on 2026-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('sigla', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'departamento',
                'ordering': ['nome'],
            },
        ),
    ]
