# Generated by Django 6.0.5 on 2026-05-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table='departamentos',
        ),
    ]
