# Generated by Django 6.0.5 on 2026-05-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('departamentos', '0002_alter_departamento_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_admissao', models.DateTimeField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('afastado', 'Afastado')], default='ativo', max_length=10)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='cargo.cargo')),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='departamentos.departamento')),
            ],
            options={
                'db_table': 'funcionarios',
                'ordering': ['nome'],
            },
        ),
    ]
