# Generated by Django 6.0.5 on 2026-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_userprofile_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de usuário', 'verbose_name_plural': 'Perfis de usuários'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primeiro_acesso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cargo_rh',
            field=models.CharField(choices=[('gerente', 'Gerente / Diretor de RH'), ('analista', 'Analista de RH')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
