# Generated by Django 6.0.5 on 2026-05-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cargo_rh',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_gerente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='setor',
            field=models.CharField(choices=[('rh', 'Recursos Humanos'), ('ti', 'Tecnologia'), ('financeiro', 'Financeiro'), ('vendas', 'Vendas'), ('marketing', 'Marketing'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
