# Generated by Django 6.0.5 on 2026-05-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_remove_userprofile_cargo_rh_userprofile_is_gerente_and_more'),
        ('departamentos', '0002_alter_departamento_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='departamentos.departamento'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
