"""
Django settings for rh_module project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BASE_DIR.parent

load_dotenv(REPO_DIR / '.env')
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--30g7h)bf^n*1wx0q((!8^d=^m0_sock%edmz1d7&v7=a3til5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'departamentos',
    'cargo',
    'funcionarios',
    'ponto',
    'ferias',
    'autenticacao',
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API do Sistema de RH',
    'DESCRIPTION': (
        'Documentação completa dos endpoints do sistema de Recursos Humanos.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COERCE_DECIMAL_TO_STRING': False,
    # Ordena os grupos (tags) no Swagger UI em ordem alfabética
    'SORT_OPERATIONS': False,
    # Define a ordem de exibição das tags no menu lateral
    'TAGS': [
        {'name': 'Cargos',            'description': 'Cadastro e gestão de cargos vinculados a departamentos.'},
        {'name': 'Departamentos',     'description': 'Cadastro e gestão dos departamentos da empresa.'},
        {'name': 'Funcionários',      'description': 'Cadastro completo de funcionários, incluindo relatório por departamento e status.'},
        {'name': 'Controle de Ponto', 'description': 'Registro de entradas e saídas, e espelho mensal de ponto por funcionário.'},
        {'name': 'Gestão de Férias',  'description': 'Solicitação, aprovação e recusa de períodos de férias.'},
    ],
    # Idioma da interface do Swagger UI
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayRequestDuration': True,
        'filter': True,
    },
    'LANGUAGE': 'pt-br',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', '').lower()

if DB_ENGINE != 'sqlite' and (DB_ENGINE == 'postgres' or os.getenv('DB_HOST')):
    DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

FUNC_API_URL = os.getenv(
    'FUNC_API_URL',
    os.getenv('FUNCIONARIOS_API_BASE_URL', 'https://italonishikawa.pythonanywhere.com'),
).rstrip('/')
FUNCIONARIOS_API_BASE_URL = (
    FUNC_API_URL if FUNC_API_URL.rstrip('/').endswith('/api') else f'{FUNC_API_URL}/api'
)
FUNCIONARIOS_API_TOKEN = os.getenv(
    'FUNCIONARIOS_API_TOKEN',
    os.getenv('FUNC_API_TOKEN', ''),
)
FUNCIONARIOS_API_USER = os.getenv('FUNC_API_USER', '')
FUNCIONARIOS_API_PASS = os.getenv('FUNC_API_PASS', '')
FUNCIONARIOS_API_TIMEOUT = int(os.getenv('FUNCIONARIOS_API_TIMEOUT', '10'))
